### ISSUE TITLE
Feedback on Blackboard xAPI examples

### ISSUE THREAD

**Issue by christoffballard** [jiscdev/xapi-vle#19]
I have reviewed the Blackboard xAPI examples which are in the rev1 branch, and have the following comments:

All examples include an object.objectType field, however I don't see this in the xAPI specification. I think the object type should refer to the target object (i.e. not be "Activity") and should be referenced in the object.definition.type field. For a course, this should refer to a course object type.

When viewing a course in moodle, the accompanying xAPI statement includes the moodle course id in context.extensions. This is then used to map the course to the corresponding academic module, via external mapping tables provided by the institution. I can't see equivalent information in the "course access" VLE example. Although it does seem to be passed in the "course_content_access" example, in object.extensions."http://adlnet.gov/expapi/activities/course".course_id. We should have a standard way of passing this information across both Moodle and Blackboard and it should pass the external identifier for the course that is known to external systems, rather than an internal identifier which is currently provided by the Moodle plugin.

In the "course_content_access" example, object.definition.type is present, but doesn't appear to provide very granular information. In the equivalent receipt, the moodle plugin currently passes the type of course content accessed by the student, e.g. folder, forum, quiz etc. We have started to use these to look at how the activity of the student breaks down into interactive, navigable and static elements. We should have a standard list of object types and both Blackboard and Moodle should generate object types for granular course elements that conform to this list.

This may just be an accidental ommission from the examples (I'm sure they'll be there in real data!), but neither "course_access" and "course_content_access" include the timestamp field.

It is really good to see the "session_timeout" example - along with the "loggedout", this will enable us to calculate student session times. However, in order to tie together activities which occur in a session with the corresponding login and either "session_timeout" or "loggedout" events, I think we need to incude a session identifier. This will make it easier to calculate session times, which would otherwise need to be calculated by pairing up adjacent events which will be computationally very expensive.

Finally, something I have made reference to in all the above comments, is the need to ensure consistency between the receipes used by both Blackboard and Moodle, which should use receipes which are agnostic of the source institution or system. This is critically important because it allows us to interpret xAPI data in a standardised way, which won't need to change depending on the source. In practice, this means that both Blackboard and Moodle should use common definitions for verbs, object types, course identifiers etc. Local definitions should be mapped to a overarching definitions defined by our xAPI data standards.

Thanks

Chris

**Comment by MiroslavKratchounov** [comment]
Thank you Chris for your feedback.

The object.objectType field is part of the xAPI specification. Please refer to https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#object.

For the Blackboard course view recipe I intentionally did not provide any context.extension wrt to a course as we decided to keep the context object absolutely the same across all recipes. My proposal would be to specify the course id in the statement object.id and not use context.extension or object.extension. In Blackboard a course id is really internal and a course is equivalent to a module. 
For the extension in  "course_content_access" I absolutely agree we need  a standard structure and properties for VLE xAPI. I also agree for "course_content_access" example, object.definition.type. We have discussed this topic but we have not come up to a decision yet. This is one of the reasons to move this discussion here to GITHub. In Blackboard course content is different from Moodle and I can imagine it will be different from other VLEs. In Blackboard there are no quiz or forum content types but there are discussions, tests, assessments etc. I absolutely agree that we need to come up with standard list of content types.

I missed the timestamp but I'll review and add it to the recipes.

I think the idea for the session identifier is good and it has been brought previously but it will be difficult to get in Blackboard. I think if you can search by the timestamp and the username you can easily determine session time.

We have taken the bottom up approach to come up from Moodle and Blackboard recipes to a standard VLE xAPI and I agree that we need to be consistent. With the Blackboard plugin we are trying to cover the basics and ensure xAPI compliance. 
In addition to your comments, according to me what is currently missing is standard way to when, where and how to use extensions. Do we use them within the statement.object or statement.context? We have to also decide on what would be the minimum data and properties required in an extension.

Thanks,
Miro

**Comment by michaelwebbjisc** [comment]
Thanks both.

Does it make sense to split into seperate issues?  @wilmTap ?

**Comment by wilmTap** [comment]
Hello, 

This is indeed an excellent starter for a whole bunch of issues that need addressing. Some can probably be sorted, but others need their own threads, I think.

**1. objectType**
I think the issue here seems to be the restrictions on what objectType can be used with, and, deeper, what 'object' means in the context of xAPI. My sense is that it is meant in the Subject-Verb-Object statement syntax meaning, rather than the more general OOP data structure meaning we might assume. 
In concrete terms than means that the spec only allows on objectType on the 'object' statement property or on the 'agent' statement property if it is being used as the object of a statement. In each case, objectType is meant to disambiguate what something is, independent of the property's role in a particular statement. The BB examples have objectType on all statement properties and have values that indicate the role in a statement rather than what they are (which is often the same, but not always)

**2. We need a standard list of VLE object types that abstract over platform specific ones.**
That's an issue that we need to address separately, I think. We can take a lead on that.

**3. Session identifier**
That's an issue where we need to come to consensus, I think. Chris, does Miro's proposal of using the timestamp and the username work for you?

**4. Platform independent recipes**
We've been working on that in the dev-refactoring branch, but more maybe required. We'd propose a state where the entities and examples are purely platform independent, and the fully worked examples are linked to one or more platform specific ones.

**5. Platform independent module ID**
One that needs a separate issue where we can explore if/how both Moodle and BB can supply such a thing.

**Comment by MiroslavKratchounov** [comment]
Just to follow up on the actor.objectType after todays JISC meeting. It is optional according to xAPI but I think we have included the objectType as it has been used by the Moodlerooms samples. 
With regard to point 5 the term module within the Blackboard context can be confusing. In Blackboard Learn module is a UI component, web page and I suppose in this context it is referred to as a parent course.

**Comment by arc12** [comment]
@MiroslavKratchounov @wilmTap re "module" - this term and "course" are horribly overloaded. I suggest we use UDD terms only as defined in UDD. As I understand things, there is a concept, which LMSs/VLEs generally have which is a top-level container which is often associated with some unit of instruction, but may also be established for other purposes (e.g. "guide to library and learning resources"). This top level entity will need to be identified and mapped to UDD entity ids. I suggest we need to agree a new term, i.e. neither "course" nor "module". I've previously used "course area", but maybe "vle unit" would do, and many others, I'm sure... 

Cheers. Ada,

**Comment by wilmTap** [comment]
Hi Miro- good catch, we ought to see whether the actor.objectType in the Moodle examples are redundant and remove them if they don't. It's not especially important, though.

As to the module identifier, let's try to resolve that at issue #2

**Comment by ds10** [comment]
I think there might have been some progress on some of these issues in [this current branch I am working on](https://github.com/jiscdev/xapi-vle/tree/dev-remastering-2) but I may be getting confused. I have some questions on wilberts points:

**item 2. We need a standard list of VLE object types that abstract over platform specific ones.**
I think I've started to pull these out in the new [vocabulary document](https://github.com/jiscdev/xapi-vle/blob/dev-remastering-2/vocabulary.md) . Does this look like the place for these?

**Item 3. Session identifier**
Is Miroslav's advice to use the separate timestamp and username to determine the session because this is a hard thing to do in blackboard?

**Item 4. Platform independent recipes**
Going forward, after [a merge of this branch](https://github.com/jiscdev/xapi-vle/blob/dev-remastering-2/vocabulary.md) each recipe should be platform independent, with links to specific examples if needed. Does this help?
