### ISSUE TITLE
Document field used to identify parent VLE course for activity

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi-vle#2]
The ability to reliably identify the parent VLE "course" for each statement is clearly important as it allows us to associate activity to the related academic module or course. We can currently see two ways of doing this. Firstly by using the courseid from .context.extensions["http://lrs.learninglocker.net/define/extensions/moodle_logstore_standard_lo…"] or by using context.contextActivities.grouping[...].extensions["http://lrs.learninglocker.net/define/extensions/moodle_course"].idnumber. This id will need to be mapped using a mapping table, but we need to be able to reliably know which id field is the appropriate one to use in all cases to avoid different interface implementations.

**Comment by christoffballard** [comment]
The field used to indicate the parent course that the activity relates to should be identified in documentation so that it can be reliably used in the data analytics pipeline.

**Comment by arc12** [comment]
I feel should not be encoded with platform-specific namespace extensions, as it is a core piece of information. The xAPI ContextActivities object is specified in terms of Activity Objects, and we can reasonably interpret as including the VLE course area. The  contexttype of "grouping" is the best fit [ignoring implied meaning of "course" and "class", which is not appropriate to our setting]:
> Grouping: an Activity with an indirect relation to the Activity which is the Object of the Statement. For example: a course that is part of a qualification. The course has several classes. The course relates to a class as the parent, the qualification relates to the class as the grouping.

The natural and conformant approach would be to use context activity object with type=grouping to encode the identity of the top level VLE container (course area). This would be mapped to module instance identifier (or programme, or ...) in a UDD data structure. The context activity structure can contain multiple entries, including multiple of type=group, so we should specify that only one of them is a course-area identifier, which should be the URL of the home page for the course area. Hence an inner join to the mapping table will find the correct module instance, even with multiple context activity entries.

Multiplicity is rather ugly IMO; it would be operationally much cleaner to have a singleton which could be found in the JSON, rather than have to deal with an array, but the xAPI spec does not allow us to add a further tag to subclass "group", and so home-in on the correct identifier. A work-around might be to require the first element in the array to be the course area identifier. This could be achieved in the plugin at the time of sending data to the LRS but AFAIK, there is no requirement for order to be preserved in the LRS, so this may be a dangerous presumption. Alternatively throw up our hands and define a jisc-namespaced extension to context where we know we can get the course area URI (NB the xAPI spec does not appear to permit extension to contextActivities).

This comes down to a judgement call: is it better to use an existing xAPI structure which is semantically OK but which introduces some clumsiness in the data handling, or to diverge and make life easier for the pilots but possibly miss a generalised approach.

I'm sorry that is rather rambling. I think this is an important decision for which we should not jump to conclusions but gather thoughts, frame rationale, and have a discussion which is in terms of the rationale.
If pushed to nail my colours to the mast, I'd sit on the fence and mix my metaphors... and suggest we require statements to BOTH a) use contextactivities.grouping and b) use a jisc.ac.uk namespaced extension to context.extensions with a key (singleton) to identifiy the umbrella course area by its home page URI.

**Comment by michaelwebbjisc** [comment]
My preference: to diverge and make life easier for the Jisc service but possibly miss a generalised approach, but make it cross platform rather than platform specific. We can iterate later.  

So from a Jisc perspective I want to focus on the minimum we need to do to make things work, and how this will affect each application.

The only info he have available for the plugin is that given by VLE, so we just need to agree where we are going to put it so devs can easier retrieve it.

We know are going to have to have a separate table mapping the VLE course to the UDD module anyway, as the VLE doesn't necessary have any info about UDD modules.

**Comment by wilmTap** [comment]
Hmmm. Since we've established that a course area is a materially different thing from module or course, and also because the grouping array is a potential pain, can I try one potentially naive possibility: rely on simple 'parent' hierarchies? That is: item a has context.contextactivities.parent test b has context.contextactivities.parent course area c etc.
How much of a pain such a solution is probably depends on how easy your tool makes it to walk property paths, I suppose.

In the event that doesn't work, I'd be happy to mock up a jisc.ac.uk namespaced extension to context.extensions and put it in the [new vocabulary page](https://github.com/jiscdev/xapi-vle/blob/dev-refactoring/vocabulary.md).

Is every tool capable of easily supplying such a course area ID, though?

**Comment by MiroslavKratchounov** [comment]
Here is a simple case of how we might represent course content relationship.

A Blackboard user Miro views a file named "xAPI for dummies" from the content area of course named "xAPI Basics".

```Javascript
{
    "version":"1.0.0",
    "id":"ad0303da-adc8-4f93-b276-30a8ef259639",
    "timestamp":"2016-02-21T03:03:39.000Z",
    "actor":{
        "objectType":"Agent",
        "name":"Miro",
        "account":{
            "homePage":"https://jisc.blackboard.com",
            "name":"miro"
        }
    },
    "verb":{
        "id":"http://id.tincanapi.com/verb/viewed",
        "display":{
            "en-US":"viewed"
        }
    },
    "object":{
        "objectType":"Activity",
        "id":"https://jisc.blackboard.com/webapps/blackboard/content/listContent.jsp?content_id=162&course_id=61",
        "definition":{
            "type":"http://adlnet.gov/expapi/activities/file",
            "name":{
                "en-US":"xAPI for dummies"
            },
            "description":{
                "en-US":"xAPI for dummies"
            }
        }
    },
    "context":{
        "contextActivities":{
            "parent":[
                "objectType":"Activity",
                "id":"https://jisc.blackboard.com/webapps/blackboard/execute/modulepage/view?course_id=1",
                "definition":{
                    "type":"http://adlnet.gov/expapi/activities/course",
                    "name":{
                        "en":"xAPI Basics"
                    },
                    "description":{
                        "en":"xAPI Basics course for Learning Analytics enthusiasts"
                    }
                ]
            },
            "platform":"Blackboard",
            "extensions":{
                "http://lrs.learninglocker.net/define/extensions/info":{
                    "https://jisc.blackboard.com":"9.1.201510",
                    "https://jisc.blackboard.com/webapps/bbc-xAPI-BBLEARN/":"1.0.12",
                    "ip":"10.3.3.48"
                }
            }
        }
    }
```

**Comment by arc12** [comment]
On the particular point of this issue (I think there are others implied by the example json).

The xAPI spec states: "Parent: an Activity with a direct relation to the Activity which is the Object of the Statement. In almost all cases there is only one sensible parent or none, not multiple. For example: a Statement about a quiz question would have the quiz as its parent Activity."

The issue is that we really want to have the ancestral node in the VLE hierarchy, not the parent.

My sense is that the use of parent, as above is problematic unless the Jisc xAPI recipes adds a requirement that parent is only ever used once with an activity type of http://adlnet.gov/expapi/activities/course.

I think it would be more consistent with the intent of the xAPI spec to use a "grouping" rather than "parent" key (while still including in the recipes a requirement that there is only ever one entry with type http://adlnet.gov/expapi/activities/course (much as I don't really like the implications of "course", this is just a URI and we can write our own description which is still consistent with the semantics of the ADL term).

Having said that, there is merit to not having to iterate through, or pattern match within, an array.

My suggestion then is to both:
1. use grouping as described to help to make the data be good generic xAPI 
2. use the jisc extension key for a singleton which contains the same ancestral course/area id as its value - i.e. http://xapi.jisc.ac.uk/extensions/parentArea (although I find "parent" to be distracting)

Adam

**Comment by MiroslavKratchounov** [comment]
Thanks, Adam.

It makes sense. I hope this reviewed sample is correct.

```Javascript{
    "version":"1.0.0",
    "id":"ad0303da-adc8-4f93-b276-30a8ef259639",
    "timestamp":"2016-02-21T03:03:39.000Z",
    "actor":{
        "objectType":"Agent",
        "name":"Miro",
        "account":{
            "homePage":"https://jisc.blackboard.com",
            "name":"miro"
        }
    },
    "verb":{
        "id":"http://id.tincanapi.com/verb/viewed",
        "display":{
            "en-US":"viewed"
        }
    },
    "object":{
        "objectType":"Activity",
        "id":"https://jisc.blackboard.com/webapps/blackboard/content/listContent.jsp?content_id=162&course_id=61",
        "definition":{
            "type":"http://adlnet.gov/expapi/activities/file",
            "name":{
                "en-US":"xAPI for dummies"
            },
            "description":{
                "en-US":"xAPI for dummies"
            }
        }
    },
    "context":{
        "contextActivities":{
            "grouping":[
                "objectType":"Activity",
                "id":"https://jisc.blackboard.com/webapps/blackboard/execute/modulepage/view?course_id=1",
                "definition":{
                    "type":"http://adlnet.gov/expapi/activities/course",
                    "name":{
                        "en-US":"xAPI Basics"
                    },
                    "description":{
                        "en-US":"xAPI Basics course for Learning Analytics enthusiasts"
                    },
                    "extensions":{
                        "http://xapi.jisc.ac.uk/extensions/parentArea":"https://jisc.blackboard.com/webapps/blackboard/execute/modulepage/view?course_id=1"
                    }
                }
            ]
        },
        "platform":"Blackboard",
        "extensions":{
            "http://lrs.learninglocker.net/define/extensions/info":{
                "https://jisc.blackboard.com":"9.1.201510",
                "https://jisc.blackboard.com/webapps/bbc-xAPI-BBLEARN/":"1.0.12"
            },
            "http://id.tincanapi.com/extension/ip-address":"10.3.3.48"
        }
    }
```

**Comment by arc12** [comment]
[not this issue, but a comment about Miroslav's example]

@MiroslavKratchounov  - I think the version of Bb should appear outside exttensions, in "version": (see https://github.com/jiscdev/xapi-vle/blob/dev-1.0/common_statements.md)

I also supopse that the learninglocker extension is really for their plugin compatibility and version information, and that it would be more appropriate to create a Bb extension for your version info, e.g.:
       "platform": "Blackboard"
       "version":"9.1.201510"
        "extensions":{
            "https://jisc.blackboard.com/webapps/bbc-xAPI-BBLEARN/":"1.0.12"
             ...
       }

I suggest the Jisc xAPI documenttion puts some obligation on plugins to disclose version information in statements, but leave the details to be platform-specific.

I'm assuming it would not be useful to have a jisc-defined extension for plugin version information, and that we'd work it out from extensions if we needed to refer to that for data quality checks, legacy hacks, etc. Maybe the experience of other folks suggests a challenge to that assumption. If so... 

Adam
                
            }

**Comment by ds10** [comment]
@arc12   http://xapi.jisc.ac.uk/extensions/parentArea is in this weeks development branch up for discussion next week, if you find you find it 'distracting' I we can put something else up for minting

**Comment by MiroslavKratchounov** [comment]
@arc12 and @ds10 There is no statement.context.version property in xAPI, that's why we chose to use a info extension. There is a revision property though.

**Comment by arc12** [comment]
@ds10 - yes please; I think that will avoid muddying the already-muddy waters of the semantics of "parent"

@MiroslavKratchounov - right you are! I should have checked the original spec. It seemed so obvious that it should exist ;-) Revision has the wrong semantics I think.

Re versions: maybe there is a need for a Jisc extension URI for platform version info and (on reflection) for plugin version info (although for the moodle plugin, this is clearly a structure), I'm fairly sure this info will be relevant: plugin version for debugging and quality checking, and the platform version may be useful if a major version change leads to change in the user experience which warrants a different interpretation of the data.

Adam

Cheers, Adam

**Comment by ds10** [comment]
@arc12  , p://xapi.jisc.ac.uk/extensions/grouping ?
@MiroslavKratchounov Good spot! this was in lifted from a google document and I never checked.

I'll add these potential extension URIs to dev branch for discussion?
