### ISSUE TITLE
"http://xapi.jisc.ac.uk/extensions/courseArea": for assignmentGraded/Submitted

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi-vle#43]
OK, I think I should have waited until I'd done the moodle plugin before saying we freeze the xAPI recipes! It's actually easier to spot small things when you are coding them....

This is a minor one I think.  We need to include 'http://xapi.jisc.ac.uk/extensions/courseArea' in the extensions for all activities that are course related.  There are missing from assignmentGraded/Submitted at the moment.

**Comment by arc12** [comment]
+1 (on both counts ;-)

definitely need to be able to match assignments activity to educational context

Adam

**Comment by ds10** [comment]
> OK, I think I should have waited until I'd done the moodle plugin before saying we freeze the xAPI recipes! It's actually easier to spot small things when you are coding them....

I've just put them in a 0.1-patch branch, I think we knew this would happen because we hadn't kicked it hard enough?

Good catch, updated those recipes in the patch branch commit [c4cef4f](https://github.com/jiscdev/xapi-vle/commit/c4cef4fbf8c719ed94eae9c3a2cf305feaf23cec) and and noticed the pull request. I'll discuss/merge on monday
