### ISSUE TITLE
Assignment submitted should include result.completion

### ISSUE THREAD

**Issue by garemoko** [jiscdev/xapi-vle#70]
Because the assignment has been completed.

**Comment by MiroslavKratchounov** [comment]
In some cases you may have multiple assignment submissions allowed.

**Comment by garemoko** [comment]
Yes. So that would be multiple completions.

**Comment by wilmTap** [comment]
Wouldn't that depend on what you'd want to record? Some assessments allow multiple submissions of the same assignment before the 'real' or 'final' submission, but not all. I don't think there's a reliable indicator of the status of the submission. 

OTOH, all assignments will be scored in some fashion, so that might make it a stronger event for sending a completion status?

**Comment by wilmTap** [comment]
The result entity has been retained as optional in v0.2, but we may want to get rid of it in the assignment submitted recipe; practice is too variable for it to be of much use in UK HE.
