### ISSUE TITLE
courseArea extension usage in assignments recipes

### ISSUE THREAD

**Issue by MiroslavKratchounov** [jiscdev/xapi-vle#79]
For assignment-submitted recipe the courseArea extension is used in "object"."definition"."extensions", on the other hand in the assignment-graded it is used in "context"."extensions" similar to Module-View. Which one is the expected usage of the courseArea extension?

**Comment by ds10** [comment]
I've made a mistake somewhere..

Looking back at the commits it looks like this was moved (by me...) as part of issue #58 https://github.com/jiscdev/xapi-vle/issues/58, but this issue states it should be in the context.extensions like the other recipes . I have misunderstood somewhere, or missed part of the conversation at the hackathon, or the issue was closed when it shouldn't be.

So, I think.. the assignment submitted recipe should have the extension in context.extensions similar to the others, and this needs to be rolled out as  a patch to 0.2 rather than waiting for 0.3.

**Comment by MiroslavKratchounov** [comment]
I thought so. For Blackboard we are implementing it in the "context"."extensions". You are right, this needs to be patched in v0.2.

**Comment by garemoko** [comment]
I think in discussion with @michaelwebbjisc at the hackathon we talked about including it both as a context extension AND as an object definition extension. Object definition extension is definitely the "right" place for it to go from an 'intention of the spec' perspective however I understand the JISC ecosystem has problems reading data from statement properties inside arrays, including context activities. (This also comes up occasionally in Watershed bugs; arrays are harder to deal with than non-arrays).

**Comment by garemoko** [comment]
The advantage of including it in the object definition (aside from it being the intended location for this sort of thing) is that systems querying the activity profile resource could fetch the data without having to dig it out of statements.

**Comment by MiroslavKratchounov** [comment]
For me it's fine either way. Blackboard is processing and transforming the data into the appropriate format and we are not familiar with the hardship of reading the data. My preference is just to be consistent across all recipes. So the question is really whether we change it for all recipes or we keep this as an exception just for assignment-graded recipe.

**Comment by ds10** [comment]
So, I add it to the context extensions of the assignment submitted recipe as a patch to 0.2 for now? And the discussion about it being included in both we leave for 0.3/call discussion

**Comment by arc12** [comment]
My rule-base for this question:
1. Consider the semantics of "courseArea"
2. consider the intention of the statement in question
3. ask to what extent the object of the statement is something which a courseArea identifier gives addtional information to, or whether it is supporting/contextual information for the entire statement (or both, I guess...)

Given what I think we mean for #1 - its about the way a VLE/LMS groups resources at a coarse level - I think we're likely to find it as context frequently, but not always (e.g. logging in is contextual to an application rather than an area within it). In matching VLE activity to a taught module and its UDD instance identifier, I'd really like to have the courseArea as context for any activity which might be identifiable as study-related. 
I can't immediately think of an example when the object would be clarified with a courseArea... but it doesn;t mean there isn't one. The assignment submission is a possibility, I suppose, but I'd prefer to see the object reflecting the sementics of a formal assessment opportunity rather than a VLE structure.

A different example where something might be an object and context is the URI for "this is a vle". In which case logging-in might reasonably define the object to be "an application of type vle" while the vle is also the context of all statements. Again, having this always in context gives us a simple filter to use when we've got statements from multiple sources in the LRW.

Adam

**Comment by garemoko** [comment]
@arc12 Just to clarify, I'm not saying that it always belongs in object.definition.extensions, I'm saying that it belongs in the definition extensions of the course object. That course object might be the object of the statement e.g. Adam Viewed Course, or it might be a [context activity](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#4162-contextactivities-property) e.g. Adam Viewed Module in Course.
